services:
  psql-db:
    image: postgres:16.4
    container_name: psqldb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "trackerdb"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d trackerdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - psql_db_data:/var/lib/postgresql/data
    networks:
      - tracker-net
    restart: always

  redis-db:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_db_data:/data
    networks:
      - tracker-net
    restart: always

  application:
    image: calorie-tracker:latest
    container_name: tracker
    build:
      context: .
    depends_on:
      psql-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - tracker-net
    restart: always

volumes:
  psql_db_data:
  redis_db_data:

networks:
  tracker-net:
    driver: bridge
