CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    age      INTEGER                                 NOT NULL,
    email    VARCHAR(255),
    height   DOUBLE PRECISION                        NOT NULL,
    name     VARCHAR(255),
    password VARCHAR(255),
    target   VARCHAR(255),
    weight   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);