CREATE TABLE dish
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    calories VARCHAR(255),
    proteins VARCHAR(255),
    fats     VARCHAR(255),
    carbs    VARCHAR(255),
    CONSTRAINT pk_dish PRIMARY KEY (id)
);