CREATE TABLE dish
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    calories INTEGER,
    proteins INTEGER,
    fats     INTEGER,
    carbs    INTEGER,
    CONSTRAINT pk_dish PRIMARY KEY (id)
);